ARG device
ARG username="corentinartaud"

FROM ubuntu:18.04 AS base-cpu
FROM nvidia/cuda:10.2-base-ubuntu18.04 AS base-gpu

FROM base-$device AS base

ARG username
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update && \
    apt-get install -y wget unzip git cmake xvfb sudo freegult3-dev ffmpeg

RUN adduser --disabled-password --gecos "Default User" $username && \
    adduser $username sudo && \
    echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    mdkir /notebooks && \
    chmod -R $username /notebooks

RUN su $username -c \
    "wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh \
    -O /tmp/anaconda3.sh" && \
    mkdir -p /opt/conda && \
    chown -R $username /opt/conda && \
    su $username -c "/bin/bash /tmp/anaconda3.sh -b -p /opt/conda -u" && \
    rm /tmp/anaconda3.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    su $username -c "echo '. /opt/conda/etc/profile.d/conda.sh' >> ~/.bashrc" && \
    su $username -c "echo 'conda activate base' >> ~/.bashrc"

ADD requirements.yaml /tmp/requirements-template.yaml

USER $username
SHELL ["bin/bash", "-i", "-c"]
RUN conda install -y jupyter

FROM base AS stage-cpu
RUN sed -e "s/{tensorflow}/tensorflow/g" -r "s/{pytorch}/pytorch/g" \ 
    /tmp/requirements-template.yaml > /tmp/requirements.yaml

FROM base AS stage-gpu
RUN sed -e "s/{tensorflow}/tensorflow-gpu/g" -r "s/{pytorch}/pytorch-gpu/g" \
    /tmp/requirements-template.yaml > /tmp/requirements.yaml

FROM stage-$device AS final

LABEL maintainer "Corentin Artaud <corentinartaud@gmail.com>"

ARG username
USER $username
SHELL ["bin/bash", "-i", "-c"]

RUN conda env create -f /tmp/requirements.yaml && \
    conda activate llp131 && \
    python -m ipykernel install --user --name python3 --display-name "Python 3"

RUN sudo rm /tmp/requirements*.yaml

EXPOSE 8888
VOLUME /notebooks
WORKDIR /notebooks
ENV PATH /opt/conda/bin:$PATH

COPY jupyter.sh /
CMD ["/jupyter.sh"]
